application: startpage-1072
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: .*
  script: main.app

- url: /static/(.*\.manifest)
  static_files: static/\1
  mime_type: text/cache-manifest
  upload: static/(.*\.manifest)

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: PIL
  version: "1.1.7"
